version: '3.8'

services:
  minio:
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /mnt/data/minio:/data/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: http://a.b.c.d:9000 # FIXME
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}

## port 9000 is used for minio api and 9001 used for minio web gui
## data is stored persistently at /mnt/data/minio