---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-sa
  namespace: mlflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      serviceAccountName: mlflow-sa
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.5.0
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          env:
          - name: MLFLOW_S3_ENDPOINT_URL
            value: "http://172.16.1.176:9000" # Adjust url
          - name: MLFLOW_S3_IGNORE_TLS
            value: "true"
          - name: MLFLOW_TRACKING_URI
            value: "http://172.16.1.176:5000" # Adjust url
          - name: AWS_ACCESS_KEY_ID
            value: "minioadmin"
          - name: AWS_SECRET_ACCESS_KEY
            value: "minioadmin"
          - name: DEFAULT_ARTIFACT_ROOT
            value: "s3://mlflow" # bucket name
          args:
            [mlflow server --host 0.0.0.0 --default-artifact-root $(DEFAULT_ARTIFACT_ROOT) --serve-artifacts]
          ports:
            - containerPort: 5000