version: '3.8'

services:
  minio:
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /mnt/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: http://a.b.c.d:9000 #Change this value to your server's IP
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}